### ISSUE TITLE
ActionMode doesn't seem to work on 2.3.4

### ISSUE THREAD

**Issue by daverix** [JakeWharton/ActionBarSherlock#162]
I get this error when running on an HTC Sensation with Sense and 2.3.4 on ActionBarSherlock 4.0 beta 4.

```
01-04 11:48:36.417: E/AndroidRuntime(22620): FATAL EXCEPTION: main
01-04 11:48:36.417: E/AndroidRuntime(22620): java.lang.NoSuchMethodError: android.view.View.setTranslationX
01-04 11:48:36.417: E/AndroidRuntime(22620):    at com.actionbarsherlock.internal.widget.ActionBarContextView.makeInAnimation(ActionBarContextView.java:386)
01-04 11:48:36.417: E/AndroidRuntime(22620):    at com.actionbarsherlock.internal.widget.ActionBarContextView.onLayout(ActionBarContextView.java:454)
01-04 11:48:36.417: E/AndroidRuntime(22620):    at android.view.View.layout(View.java:7292)
01-04 11:48:36.417: E/AndroidRuntime(22620):    at android.widget.FrameLayout.onLayout(FrameLayout.java:338)
01-04 11:48:36.417: E/AndroidRuntime(22620):    at com.actionbarsherlock.internal.widget.ActionBarContainer.onLayout(ActionBarContainer.java:195)
01-04 11:48:36.417: E/AndroidRuntime(22620):    at android.view.View.layout(View.java:7292)
01-04 11:48:36.417: E/AndroidRuntime(22620):    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1254)
01-04 11:48:36.417: E/AndroidRuntime(22620):    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1130)
01-04 11:48:36.417: E/AndroidRuntime(22620):    at android.widget.LinearLayout.onLayout(LinearLayout.java:1047)
01-04 11:48:36.417: E/AndroidRuntime(22620):    at android.view.View.layout(View.java:7292)
01-04 11:48:36.417: E/AndroidRuntime(22620):    at android.widget.FrameLayout.onLayout(FrameLayout.java:338)
01-04 11:48:36.417: E/AndroidRuntime(22620):    at android.view.View.layout(View.java:7292)
01-04 11:48:36.417: E/AndroidRuntime(22620):    at android.widget.FrameLayout.onLayout(FrameLayout.java:338)
01-04 11:48:36.417: E/AndroidRuntime(22620):    at android.view.View.layout(View.java:7292)
01-04 11:48:36.417: E/AndroidRuntime(22620):    at android.view.ViewRoot.performTraversals(ViewRoot.java:1205)
01-04 11:48:36.417: E/AndroidRuntime(22620):    at android.view.ViewRoot.handleMessage(ViewRoot.java:1961)
01-04 11:48:36.417: E/AndroidRuntime(22620):    at android.os.Handler.dispatchMessage(Handler.java:99)
01-04 11:48:36.417: E/AndroidRuntime(22620):    at android.os.Looper.loop(Looper.java:150)
01-04 11:48:36.417: E/AndroidRuntime(22620):    at android.app.ActivityThread.main(ActivityThread.java:4293)
01-04 11:48:36.417: E/AndroidRuntime(22620):    at java.lang.reflect.Method.invokeNative(Native Method)
01-04 11:48:36.417: E/AndroidRuntime(22620):    at java.lang.reflect.Method.invoke(Method.java:507)
01-04 11:48:36.417: E/AndroidRuntime(22620):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:849)
01-04 11:48:36.417: E/AndroidRuntime(22620):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:607)
01-04 11:48:36.417: E/AndroidRuntime(22620):    at dalvik.system.NativeStart.main(Native Method)
```

It does work fine when running in emulator with android 4.0.3. I'm using the Theme.Sherlock theme.

Here is the imports I'm using:

``` java
package nu.laurell.links.fragments;

import java.util.ArrayList;
import java.util.List;

import com.actionbarsherlock.view.ActionMode;
import com.actionbarsherlock.view.Menu;
import com.actionbarsherlock.view.MenuInflater;
import com.actionbarsherlock.view.MenuItem;

import nu.laurell.links.R;
import nu.laurell.links.SaveLinkActivity;
import nu.laurell.links.actions.GetLinksAction;
import nu.laurell.links.actions.RemoveLinkAction;
import nu.laurell.links.actions.ReplaceTagsAction;
import nu.laurell.links.model.Link;
import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.support.v4.app.ListFragment;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.view.ContextMenu.ContextMenuInfo;
import android.widget.AdapterView.AdapterContextMenuInfo;
import android.widget.BaseAdapter;
import android.widget.CheckBox;
import android.widget.CompoundButton;
import android.widget.LinearLayout;
import android.widget.ListView;
import android.widget.TextView;
```

Here is the ActionMode.Callback:

``` java
    private ActionMode.Callback mActionModeCallback = new ActionMode.Callback() {
        @Override
        public boolean onPrepareActionMode(ActionMode mode, Menu menu) {

            return false;
        }

        @Override
        public void onDestroyActionMode(ActionMode mode) {
            mCurrentActionMode = null;
            unselectAll();
        }

        @Override
        public boolean onCreateActionMode(ActionMode mode, Menu menu) {
            MenuInflater inflater = getActivity().getSupportMenuInflater();
            inflater.inflate(R.menu.links_actionmode, menu);
            return true;
        }

        @Override
        public boolean onActionItemClicked(ActionMode mode, MenuItem item) {
            switch(item.getItemId()) {
            case R.id.menuRemoveSelected:
                showRemoveSelectionDialog();
                mode.finish();
                return true;
            case R.id.menuChangeTags:
                showReplaceTags();
                mode.finish();
                return true;
            default:
                return false;
            }
        }
    };
```

Here is the code for starting the ActionMode and it's what trigging the error:

``` java
    private void showActionMode() {
        if(mCurrentActionMode == null)
            mCurrentActionMode = getActivity().startActionMode(mActionModeCallback);

        mCurrentActionMode.setTitle(getSelectedItemsCount() + " selected items");
    }
```

Could be me that's doing it wrong or could be a bug.

**Comment by JakeWharton** [comment]
The animation which brings the action mode's views in seems to be using a method that is API 11+ only. Relates to #138.

Brilliant bug report! Thanks.

**Comment by JakeWharton** [comment]
Closing this issue. Updated the linked issue to cover both action bar and modes since they're the same problem.
