### ISSUE TITLE
action bar supprot for 2.2

### ISSUE THREAD

**Issue by chandujujare** [JakeWharton/ActionBarSherlock#1076]
hi i am chandu 

i want to give actionbar  support for 2.2 versions i am unable to give it 

please tell me which i want to version of actionbarsherlock i have to download and how to integrate?

**Comment by JakeWharton** [comment]
Every version supports Android 2.2.

**Comment by chandujujare** [comment]
i added to 2.2 it gives the issues

actionbarsherlock\res\values-v14\abs__themes.xml:6: error: Error retrieving parent for item: No resource found that matches the given name 'android:Theme.Holo.Light'.
actionbarsherlock\res\values-v14\abs__themes.xml:8: error: Error retrieving parent for item: No resource found that matches the given name 'android:Theme.Holo.Light.DarkActionBar'

like more than 20 issues 
how to fix those

**Comment by JakeWharton** [comment]
You have to compile with Android 4.0 or newer.

**Comment by chandujujare** [comment]
if i compile with 4.0 is it works in 2.2 device

**Comment by JakeWharton** [comment]
Yes. More info here: http://simonvt.net/2012/02/07/what-api-level-should-i-target/

**Comment by chandujujare** [comment]
but i tried it 2.1 device it doen't work do u know y it is?

**Comment by JakeWharton** [comment]
Not without more info

**Comment by chandujujare** [comment]
i done as defined in more info but its not worked

got this issue
java.lang.NoSuchMethodError: com.ntc.bhihakhims.LoginActivity.getActionBar

**Comment by serj-lotutovici** [comment]
You have to use getSupportActionBar() method. Which you will find in any SherlockActivity.

**Comment by chandujujare** [comment]
hi @serj-lotutovici 

how to use that getspportaction bar and plz provide for some android 2.2 example

**Comment by serj-lotutovici** [comment]
For example, you have an activity:

```
public class Simple extends SherlockActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        // Here you can setup the actionbar
        getSupportActionBar().setTitle("Hello!");
    }
}
```

ABS will use the appropriate method depending on the OS version, on what you app will run. (On Android 4.0 it will call the getActionBar() method, on lower versions it will do it's compatibility job.)

I would suggest you to give a closer look on the samples that Jake Warton provides with ABS. Yo can finde them here https://github.com/JakeWharton/ActionBarSherlock/tree/master/actionbarsherlock-samples.
