### ISSUE TITLE
Errors when compiling with IntelliJ IDEA

### ISSUE THREAD

**Issue by ai212983** [JakeWharton/ActionBarSherlock#92]
When compiling with IntelliJ IDEA, following errors will occur:

_path to the source_\src\com\actionbarsherlock\internal\view\menu\MenuItemImpl.java
    Error:Error:line (39)com.actionbarsherlock.internal.view.menu.MenuItemImpl is not abstract and does not override abstract method isActionViewExpanded() in android.view.MenuItem

_path to the source_\src\com\actionbarsherlock\internal\view\menu\MenuItemWrapper.java
    Error:Error:line (35)com.actionbarsherlock.internal.view.menu.MenuItemWrapper is not abstract and does not override abstract method setOnActionExpandListener(android.view.MenuItem.OnActionExpandListener) in android.view.MenuItem

_path to the source_\src\com\actionbarsherlock\internal\view\menu\ActionMenuItem.java
    Error:Error:line (11)com.actionbarsherlock.internal.view.menu.ActionMenuItem is not abstract and does not override abstract method collapseActionView() in android.view.MenuItem

After implementing dummy methods, everything is fine. Not sure if this problem remains with another compilers (I guess not).

**Comment by JakeWharton** [comment]
This is an error that has to do with what version of the JDK you are compiling with. Interface `@Override` support was added in Java 1.6 / 6.

You _should_ be able to change this by going to Project Structure -> Project -> Project SDK. I'm not an IDEA user though so that location may have changed slightly.

**Comment by ai212983** [comment]
Yeah, I had that issues about overriding interfaces (and they had another error messages), fixed by switching project sdk / language level. I'll recheck that, though.

**Comment by ai212983** [comment]
Just rechecked it - with language level 6 (overrides for interfaces) and SDK 6 Update 20 problem is still here. I don't mind this issue closed though, as it works just fine with dummy methods in above-mentioned classes.

**Comment by JakeWharton** [comment]
Well I know that compilation through both Maven and Eclipse works with Java 1.6 specification. I haven't used IDEA for Android development (or even at all recently) but I'll try to set it up today or tonight and test it out.

You definitely shouldn't need to update anything though to get compilation working.

**Comment by ai212983** [comment]
Yeah, thanks a lot for that - I love this IDE and would hate to move to Eclipse. =)

Thanks again.

**Comment by Xomo** [comment]
I have the same error while compiling using Android 4.0.1 with IDEA.
Until this is fixed I need to go back to Android 3.2 and everything is working well then.
It would be nice to keep this issue open!
Thanks.

**Comment by JakeWharton** [comment]
I apparently didn't read the original bug report. Android 4.0 compilation is
not supported because it introduces new APIs that's cannot be easily
supported. You can add the empty stubs for noe just be sure to not use them.

Support for this will come in ABS v4. Sorry for leading you on a wild goose
chase.

---

Jake Wharton
http://about.me/jakewharton
On Oct 27, 2011 5:27 PM, "Xomo" <
reply@reply.github.com>
wrote:

**Comment by Xomo** [comment]
Ok, I wrote the Android version to be sure we were speaking about the same issue and that was useful :)
I'll wait for ABS 4, thanks!
